### PR TITLE
Remove Gemfile.lock otherwise:

### PR DESCRIPTION
**Pull request by n-rodriguez**
```
Bundler could not find compatible versions for gem "rack":
  In Gemfile:
    rails (= 4.2.6) was resolved to 4.2.6, which depends on
      railties (= 4.2.6) was resolved to 4.2.6, which depends on
        actionpack (= 4.2.6) was resolved to 4.2.6, which depends on
          rack (~> 1.6)

    gitlab-grack (~> 2.0.2) was resolved to 2.0.2, which depends on
      rack (~> 1.5.1)
```

### CODE REVIEW

**Comment by jacobvosmaer** [comment]
Thanks! Not sure if we (GitLab) can do anything with this. We don't use Grack anymore ourselves. I updated this project's description to reflect that.

**Comment by n-rodriguez** [comment]
Hi! Thanks for your answer. Do you think it has a chance to be merged?

**Comment by n-rodriguez** [comment]
Hi there! Any news?

**Comment by jacobvosmaer** [comment]
Wow it's been a year. Sorry about that.

@n-rodriguez this repo is read-only as far as GitLab Inc. is concerned. If you want to build on this fork-of-a-fork the best thing to do would be to fork it yourself. Thanks again for the PR!

**Pull request closed without merging**
